### ISSUE TITLE
Bump Lodash for security

### ISSUE THREAD

**Issue by SubJunk** [keymetrics/vizion#28]
Users of vizion are getting these security warnings on GitHub that can be resolved by using the latest version of Lodash, please bump it

https://github.com/UniversalMediaServer/api/issues/47
https://github.com/UniversalMediaServer/api/issues/48
https://github.com/UniversalMediaServer/api/issues/49

**Comment by Unitech** [comment]
lodash bumped

**Comment by SubJunk** [comment]
That was fast, thanks!
